[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kconfig"
version = "1.1.1"
description = "Reverse-engineer kernel .config files."
authors = [{ name = "heavycircle" }]
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
dependencies = [
    "requests>=2.34.2",
    "rich>=15.0.0",
    "sympy>=1.14.0",
    "tree-sitter>=0.25.2",
    "tree-sitter-c>=0.24.2",
    "typer>=0.26.5",
]

[dependency-groups]
dev = [
    "codespell>=2.4.2",
    "deptry>=0.25.1",
    "mypy>=2.1.0",
    "ruff>=0.15.13",
    "vulture>=2.16",
]

[project.scripts]
kconfig = "kconfig.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["kconfig"]

# --- Deptry ---------------------------------------------------

[tool.deptry]
known_first_party = ["kconfig"]

# --- Ruff -----------------------------------------------------

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN401",  # typing.Any not allowed
    "COM812",  # Missing trailing comma
    "D100",    # Missing docstring in public module
    "D104",    # Missing docstring in public package
    "D107",    # Missing docstring in __init__
    "EM101",   # Exceptions must not use a string literal
    "EM102",   # Exceptions must not use an f-string literal
    "FBT001",  # Boolean-typed positional argument in function definition
    "FBT002",  # Boolean default positional argument in function definition
    "FBT003",  # Boolean positional value in function call
    "FIX002",  # Line contains TODO, consider resolving the issue
    "PLR2004", # Magic values in comparisons
    "PLW0603", # Using 'global' to edit globals
    "TRY003",  # Avoid specifying long messages outside the exception class
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
known-first-party = ["kconfig"]
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.pydocstyle]
convention = "google"

# --- Mypy -----------------------------------------------------

[tool.mypy]
python_version = "3.10"
exclude = ["tests/"]
explicit_package_bases = true
strict = true
disallow_any_unimported = true
local_partial_types = true
strict_bytes = true
enable_error_code = [
    "ignore-without-code",
    "truthy-bool",
    "truthy-iterable",
    "redundant-self",
    "redundant-expr",
    "possibly-undefined",
    "explicit-override",
    "deprecated",
]
show_column_numbers = true
show_error_codes = true
follow_imports = "silent"
follow_untyped_imports = true
