[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kconfig"
version = "0.1.0"
description = "Reverse kernel .config files."
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["tree-sitter>=0.25.2", "tree-sitter-c>=0.24.2"]

[project.scripts]
kconfig = "kconfig.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["kconfig"]

[tool.pylint.format]
max-line-length = 120

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "I", "F", "B", "C90", "PL", "TC", "UP", "FA"]
ignore = [
    "PLR2004", # Magic values in comparisons
    "PLW0603", # Using 'global' to edit globals
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
known-first-party = []
lines-after-imports = 2
required-imports = ["from __future__ import annotations"]
